#!/bin/bash
set -ex

export KERNEL_BASE_VER=linux-${KERNEL_BASE_VER}
export XANMOD_CONFIG=config_x86-64-v2

# define outer
#export WORK_DIR=/dev/shm/linux
#export KERNEL_BASE_URL=https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.12.tar.xz
#export XANMOD_PATCH=https://sourceforge.net/projects/xanmod/files/releases/edge/6.12.1-xanmod1/patch-6.12.1-xanmod1.xz/download

sudo -E rm -rf ${WORK_DIR} || true
mkdir -p ${WORK_DIR} || true

## https://blobfolio.com/2024/building-a-custom-xanmod-kernel-on-ubuntu-23-10/
# if not exist llvm19 then build it
[ ! -e /opt/llvm19_krl ] && build_xanmod_docker.sh


# download source
curl -L ${KERNEL_BASE_URL}  -o /dev/shm/linux.tar.xz
curl -L ${XANMOD_PATCH}  -o /dev/shm/patch.xz

# Unpack the kernel sources and patches
cd ${WORK_DIR} && tar -xJf /dev/shm/linux.tar.xz && unxz -k /dev/shm/patch.xz
cd ${WORK_DIR}/${KERNEL_BASE_VER}
patch -Np1 -i /dev/shm/patch
rm /dev/shm/linux.tar.xz && rm /dev/shm/patch*

## https://github.com/graysky2/openwrt/commit/0628c0a4673ad349d517b579e72d88de9c3924a5#diff-d5daeb65b3fa0ba33c79958bd89ca5122a6211baa492081ed752652a9a1bbdd1R20
## CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE  boost build
sed -i "s/KBUILD_CFLAGS += -O2/KBUILD_CFLAGS += -O3/g" arch/x86/Makefile 
cat arch/x86/Makefile | grep KBUILD_CFLAGS

# build kernel
cp -a CONFIGS/xanmod/gcc/${XANMOD_CONFIG} .config
export MAIN_KCONFIG_FILE=.config

# enable kvm and disable xen
sed -i 's/CONFIG_XEN=[mny]/CONFIG_XEN=n/g'  			${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_HAVE_KVM=[mny]/CONFIG_HAVE_KVM=y/g'		${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_MODULE_COMPRESS_XZ=[mny]/CONFIG_MODULE_COMPRESS_XZ=y/g'  		${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_MODULE_DECOMPRESS=[mny]/CONFIG_MODULE_DECOMPRESS=y/g'  		${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_FW_LOADER_COMPRESS_ZSTD=[mny]/CONFIG_FW_LOADER_COMPRESS_ZSTD=y/g'  		${MAIN_KCONFIG_FILE}

# disable gpu
sed -i 's/CONFIG_DRM_AMDGPU=[mny]/CONFIG_DRM_AMDGPU=n/g'  	${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_DRM_RADEON=[mny]/CONFIG_DRM_RADEON=n/g'  	${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_DRM_NOUVEAU=[mny]/CONFIG_DRM_NOUVEAU=n/g'  	${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_DRM_XE=[mny]/CONFIG_DRM_XE=n/g'  		${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_INPUT_TOUCHSCREEN=[mny]/CONFIG_INPUT_TOUCHSCREEN=n/g'  ${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_SURFACE_PLATFORMS=[mny]/CONFIG_SURFACE_PLATFORMS=n/g'  ${MAIN_KCONFIG_FILE}

sed -i 's/CONFIG_HAVE_KERNEL_BZIP2=[mny]/CONFIG_HAVE_KERNEL_BZIP2=n/g'  ${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_HAVE_KERNEL_LZO=[mny]/CONFIG_HAVE_KERNEL_LZO=n/g'  	${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_HYPERV=[mny]/CONFIG_HYPERV=y/g'  			${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_VMXNET3=[mny]/CONFIG_VMXNET3=y/g' 			${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_TLS=[mny]/CONFIG_TLS=y/g' 				${MAIN_KCONFIG_FILE}

sed -i 's/CONFIG_WIRELESS=[mny]/CONFIG_WIRELESS=n/g' 			${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_WIRELESS_HOTKEY=[mny]/CONFIG_WIRELESS_HOTKEY=n/g'  	${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_SFC=[mny]/CONFIG_SFC=n/g'  				${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_SFC_FALCON=[mny]/CONFIG_SFC_FALCON=n/g'  			${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_SFC_SIENA=[mny]/CONFIG_SFC_SIENA=n/g'  			${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_NET_VENDOR_MARVELL=[mny]/CONFIG_NET_VENDOR_MARVELL=n/g'  	${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_NET_VENDOR_CAVIUM=[mny]/CONFIG_NET_VENDOR_CAVIUM=n/g'  	${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_NET_VENDOR_NETRONOME=[mny]/CONFIG_NET_VENDOR_NETRONOME=n/g'  	${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_NET_DSA_MV88E6060=[mny]/CONFIG_NET_DSA_MV88E6060=n/g'  	${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_NET_DSA_MV88E6XXX=[mny]/CONFIG_NET_DSA_MV88E6XXX=n/g'  	${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_NET_DSA_SJA1105=[mny]/CONFIG_NET_DSA_SJA1105=n/g' 	 	${MAIN_KCONFIG_FILE}

sed -i 's/CONFIG_BT=[mny]/CONFIG_BT=n/g'  			${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_WLAN=[mny]/CONFIG_WLAN=n/g' 			${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_ISDN=[mny]/CONFIG_ISDN=n/g'  			${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_NEW_LEDS=[mny]/CONFIG_NEW_LEDS=n/g'  		${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_NFC=[mny]/CONFIG_NFC=n/g'  			${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_INFINIBAND=[mny]/CONFIG_INFINIBAND=n/g'  	${MAIN_KCONFIG_FILE}

sed -i 's/CONFIG_SOUND=[mny]/CONFIG_SOUND=n/g' 		${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_SOUNDWIRE=[ymn]/CONFIG_SOUNDWIRE=n/g'  	${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_MEDIA_SUPPORT=[mny]/CONFIG_MEDIA_SUPPORT=n/g' ${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_VIDEO_DEV=[mny]/CONFIG_VIDEO_DEV=n/g' 	${MAIN_KCONFIG_FILE}

sed -i 's/CONFIG_BCACHEFS_FS=[mny]/CONFIG_BCACHEFS_FS=n/g' 	${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_BCACHE=[mny]/CONFIG_BCACHE=n/g' 		${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_BTRFS_FS=[mny]/CONFIG_BTRFS_FS=n/g' 		${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_OCFS2_FS=[mny]/CONFIG_OCFS2_FS=n/g' 		${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_F2FS_FS=[mny]/CONFIG_F2FS_FS=n/g' 		${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_GFS2_FS=[mny]/CONFIG_GFS2_FS=n/g' 		${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_JFFS2_FS=[mny]/CONFIG_JFFS2_FS=n/g' 		${MAIN_KCONFIG_FILE}

sed -i '/CONFIG_GPIO_BT8XX/e' ${MAIN_KCONFIG_FILE}
echo 'CONFIG_GPIO_BT8XX=n' >> ${MAIN_KCONFIG_FILE}

echo 'CONFIG_DEBUG_INFO_NONE=y' >> ${MAIN_KCONFIG_FILE}
echo 'CONFIG_DEBUG_INFO_DWARF4=n' >> ${MAIN_KCONFIG_FILE}
echo 'CONFIG_DEBUG_INFO_DWARF5=n' >> ${MAIN_KCONFIG_FILE}
echo 'CONFIG_DEBUG_INFO_DWARF_TOOLCHAIN_DEFAULT=n' >> ${MAIN_KCONFIG_FILE}

# for xdp https://pulsar.sh/docs/faq/kernel-requirements
sed -i 's/CONFIG_TEST_/# CONFIG_TEST_/g' 			${MAIN_KCONFIG_FILE}

echo 'CONFIG_TEST_BPF=n' >> ${MAIN_KCONFIG_FILE}
echo 'CONFIG_DEBUG_INFO=y' >> ${MAIN_KCONFIG_FILE}
echo 'CONFIG_DEBUG_INFO_BTF=y' >> ${MAIN_KCONFIG_FILE}
echo 'CONFIG_SECURITY=y' >> ${MAIN_KCONFIG_FILE}
echo 'CONFIG_SECURITYFS=y' >> ${MAIN_KCONFIG_FILE}
echo 'CONFIG_SECURITY_NETWORK=y' >> ${MAIN_KCONFIG_FILE}
echo 'CONFIG_FUNCTION_TRACER=y' >> ${MAIN_KCONFIG_FILE}
echo 'CONFIG_FTRACE_SYSCALLS=y' >> ${MAIN_KCONFIG_FILE}
echo 'CONFIG_BPF_LSM=y' >> ${MAIN_KCONFIG_FILE}

##### cloud 
sed -i 's/CONFIG_HW_CONSOLE=[mny]/CONFIG_HW_CONSOLE=n/g'		${MAIN_KCONFIG_FILE}

sed -i 's/CONFIG_UBSAN=[mny]/CONFIG_UBSAN=n/g' 		${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_FONTS=[mny]/CONFIG_FONTS=n/g' 		${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_AS3935=[mny]/CONFIG_AS3935=n/g' 	${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_THINKPAD_ACPI=[mny]/CONFIG_THINKPAD_ACPI=n/g' 		${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_VME_USER=[mny]/CONFIG_VME_USER=n/g' 	${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_LTE_GDM724X=[mny]/CONFIG_LTE_GDM724X=n/g' 		${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_GREYBUS=[mny]/CONFIG_GREYBUS=n/g' 	${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_COMEDI=[mny]/CONFIG_COMEDI=n/g' 	${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_LEDS_CLASS=[mny]/CONFIG_LEDS_CLASS=n/g' 		${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_MMC=[mny]/CONFIG_MMC=n/g' 		${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_TYPEC=[mny]/CONFIG_TYPEC=n/g' 		${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_USB_NET_DRIVERS=[mny]/CONFIG_USB_NET_DRIVERS=n/g'	${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_USB_USBNET=[mny]/CONFIG_USB_USBNET=n/g' 		${MAIN_KCONFIG_FILE}

sed -i 's/CONFIG_MTD=[mny]/CONFIG_MTD=n/g'  			${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_BNX2X=[mny]/CONFIG_BNX2X=n/g'  		${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_QED=[mny]/CONFIG_QED=n/g'  			${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_QLCNIC=[mny]/CONFIG_QLCNIC=n/g'  		${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_NET_VENDOR_CHELSIO=[mny]/CONFIG_NET_VENDOR_CHELSIO=n/g'  	${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_NET_VENDOR_META=[mny]/CONFIG_NET_VENDOR_META=n/g'  		${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_NET_VENDOR_MICREL=[mny]/CONFIG_NET_VENDOR_MICREL=n/g'  	${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_NET_VENDOR_MYRI=[mny]/CONFIG_NET_VENDOR_MYRI=n/g'  		${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_NET_VENDOR_NATSEMI=[mny]/CONFIG_NET_VENDOR_NATSEMI=n/g'  	${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_NET_VENDOR_NVIDIA=[mny]/CONFIG_NET_VENDOR_NVIDIA=n/g'  	${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_NET_VENDOR_OKI=[mny]/CONFIG_NET_VENDOR_OKI=n/g'  		${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_NET_VENDOR_QLOGIC=[mny]/CONFIG_NET_VENDOR_QLOGIC=n/g'  	${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_NET_VENDOR_QUALCOMM=[mny]/CONFIG_NET_VENDOR_QUALCOMM=n/g'	${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_NET_VENDOR_RDC=[mny]/CONFIG_NET_VENDOR_RDC=n/g'		${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_NET_VENDOR_RENESAS=[mny]/CONFIG_NET_VENDOR_RENESAS=n/g'	${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_NET_VENDOR_SMSC=[mny]/CONFIG_NET_VENDOR_SMSC=n/g'	${MAIN_KCONFIG_FILE}

sed -i 's/CONFIG_TABLET/# CONFIG_TABLET/g' 			${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_CHARGER_/# CONFIG_CHARGER_/g' 			${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_BATTERY/# CONFIG_BATTERY/g' 			${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_LEDS/# CONFIG_LEDS/g' 				${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_ARCNET=[mny]/CONFIG_ARCNET=n/g'  			${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_B53=[mny]/CONFIG_B53=n/g'  			${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_JOYSTICK/#CONFIG_JOYSTICK/g'  			${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_INPUT_TABLET=[mny]/CONFIG_INPUT_TABLET=n/g'  			${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_INPUT_TOUCHSCREEN=[mny]/CONFIG_INPUT_TOUCHSCREEN=n/g'  			${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_FRAME_WARN=1024/CONFIG_FRAME_WARN=2048/g'  			${MAIN_KCONFIG_FILE}

#sed -i 's/CONFIG_IIO=[mny]/CONFIG_IIO=n/g' 			${MAIN_KCONFIG_FILE}
#sed -i 's/CONFIG_PMBUS=[mny]/CONFIG_PMBUS=n/g' 		${MAIN_KCONFIG_FILE}
#sed -i 's/CONFIG_SENSORS/# CONFIG_SENSORS/g' 			${MAIN_KCONFIG_FILE}
#sed -i 's/CONFIG_KGDB=[mny]/CONFIG_KGDB=n/g' 			${MAIN_KCONFIG_FILE}
#sed -i 's/CONFIG_PHYLIB=[mny]/CONFIG_PHYLIB=n/g' 		${MAIN_KCONFIG_FILE}
#sed -i 's/CONFIG_DRM_I915=[mny]/CONFIG_DRM_I915=n/g'  		${MAIN_KCONFIG_FILE}
#sed -i 's/CONFIG_I40E=[mny]/CONFIG_I40E=n/g'  			${MAIN_KCONFIG_FILE}
#sed -i 's/CONFIG_ICE=[mny]/CONFIG_ICE=n/g'  			${MAIN_KCONFIG_FILE}
#sed -i 's/CONFIG_MLX5_/# CONFIG_MLX5_/g' 			${MAIN_KCONFIG_FILE}

if [ ! -z "$BUILD_TYPE"  ]; then
  sed -i 's/CONFIG_PC104=[mny]/CONFIG_PC104=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_IOSF_MBI=[mny]/CONFIG_IOSF_MBI=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_IOSF_MBI_DEBUG=[mny]/CONFIG_IOSF_MBI_DEBUG=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_GART_IOMMU=[mny]/CONFIG_GART_IOMMU=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_X86_MCELOG_LEGACY=[mny]/CONFIG_X86_MCELOG_LEGACY=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_X86_16BIT=[mny]/CONFIG_X86_16BIT=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_PM_WAKELOCKS=[mny]/CONFIG_PM_WAKELOCKS=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_PM_DEBUG=[mny]/CONFIG_PM_DEBUG=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_PM_TRACE=[mny]/CONFIG_PM_TRACE=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_ACPI_DEBUGGER=[mny]/CONFIG_ACPI_DEBUGGER=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_ACPI_AC=[mny]/CONFIG_ACPI_AC=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_ACPI_BATTERY=[mny]/CONFIG_ACPI_BATTERY=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_ACPI_IPMI=[mny]/CONFIG_ACPI_IPMI=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_ACPI_DEBUG=[mny]/CONFIG_ACPI_DEBUG=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_ACPI_BGRT=[mny]/CONFIG_ACPI_BGRT=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_ACPI_NHLT=[mny]/CONFIG_ACPI_NHLT=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_ACPI_DPTF=[mny]/CONFIG_ACPI_DPTF=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_ISA_BUS=[mny]/CONFIG_ISA_BUS=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_ISA_DMA_API=[mny]/CONFIG_ISA_DMA_API=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_ZSWAP=[mny]/CONFIG_ZSWAP=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_ANON_VMA_NAME=[mny]/CONFIG_ANON_VMA_NAME=n/g'  			${MAIN_KCONFIG_FILE}
  
  sed -i 's/CONFIG_INET_ESPINTCP=[mny]/CONFIG_INET_ESPINTCP=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_IPV6_IOAM6_LWTUNNEL=[mny]/CONFIG_IPV6_IOAM6_LWTUNNEL=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_NETFILTER_NETLINK_HOOK=[mny]/CONFIG_NETFILTER_NETLINK_HOOK=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_ATM=[mny]/CONFIG_ATM=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_BRIDGE_MRP=[mny]/CONFIG_BRIDGE_MRP=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_BRIDGE_CFM=[mny]/CONFIG_BRIDGE_CFM=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_NET_DSA=[mny]/CONFIG_NET_DSA=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_LLC2=[mny]/CONFIG_LLC2=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_ATALK=[mny]/CONFIG_ATALK=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_LAPB=[mny]/CONFIG_LAPB=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_PHONET=[mny]/CONFIG_PHONET=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_6LOWPAN=[mny]/CONFIG_6LOWPAN=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_IEEE802154=[mny]/CONFIG_IEEE802154=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_MAC802154=[mny]/CONFIG_MAC802154=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_BATMAN_ADV=[mny]/CONFIG_BATMAN_ADV=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_HSR=[mny]/CONFIG_HSR=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_QRTR=[mny]/CONFIG_QRTR=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_NET_NCSI=[mny]/CONFIG_NET_NCSI=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_HAMRADIO=[mny]/CONFIG_HAMRADIO=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_AX25=[mny]/CONFIG_AX25=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_NETROM=[mny]/CONFIG_NETROM=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_ROSE=[mny]/CONFIG_ROSE=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_6PACK=[mny]/CONFIG_6PACK=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_MKISS=[mny]/CONFIG_MKISS=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_BPQETHER=[mny]/CONFIG_BPQETHER=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_YAM=[mny]/CONFIG_YAM=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_BAYCOM_PAR=[mny]/CONFIG_BAYCOM_PAR=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_BAYCOM_SER_HDX=[mny]/CONFIG_BAYCOM_SER_HDX=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_BAYCOM_SER_FDX=[mny]/CONFIG_BAYCOM_SER_FDX=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_CAN=[mny]/CONFIG_CAN=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_BT=[mny]/CONFIG_BT=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_RXKAD=[mny]/CONFIG_RXKAD=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_WIRELESS=[mny]/CONFIG_WIRELESS=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_CFG80211=[mny]/CONFIG_CFG80211=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_LIB80211=[mny]/CONFIG_LIB80211=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_MAC80211=[mny]/CONFIG_MAC80211=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_RFKILL=[mny]/CONFIG_RFKILL=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_NET_9P=[mny]/CONFIG_NET_9P=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_CAIF=[mny]/CONFIG_CAIF=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_NFC=[mny]/CONFIG_NFC=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_PCIE_EDR=[mny]/CONFIG_PCIE_EDR=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_PCI_STUB=[mny]/CONFIG_PCI_STUB=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_PCI_NPEM=[mny]/CONFIG_PCI_NPEM=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_PCI_P2PDMA=[mny]/CONFIG_PCI_P2PDMA=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_VMD=[mny]/CONFIG_VMD=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_PCIE_DW=[mny]/CONFIG_PCIE_DW=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_PCI_ENDPOINT=[mny]/CONFIG_PCI_ENDPOINT=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_PCI_SW_SWITCHTEC=[mny]/CONFIG_PCI_SW_SWITCHTEC=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_PCCARD=[mny]/CONFIG_PCCARD=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_PCMCIA=[mny]/CONFIG_PCMCIA=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_CARDBUS=[mny]/CONFIG_CARDBUS=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_YENTA=[mny]/CONFIG_YENTA=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_PD6729=[mny]/CONFIG_PD6729=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_I82092=[mny]/CONFIG_I82092=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_RAPIDIO=[mny]/CONFIG_RAPIDIO=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_MHI_BUS_EP=[mny]/CONFIG_MHI_BUS_EP=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_EDD=[mny]/CONFIG_EDD=m/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_EFI_TEST=[mny]/CONFIG_EFI_TEST=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_GNSS=[mny]/CONFIG_GNSS=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_MTD=[mny]/CONFIG_MTD=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_FTL=[mny]/CONFIG_FTL=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_NFTL=[mny]/CONFIG_NFTL=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_RFD_FTL=[mny]/CONFIG_RFD_FTL=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_SRAM=[mny]/CONFIG_SRAM=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_NSM=[mny]/CONFIG_NSM=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_XILINX_SDFEC=[mny]/CONFIG_XILINX_SDFEC=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_C2PORT=[mny]/CONFIG_C2PORT=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_EEPROM/#CONFIG_EEPROM/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_CB710_CORE=[mny]/CONFIG_CB710_CORE=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_INTEL_MEI=[mny]/CONFIG_INTEL_MEI=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_SCSI_SRP_ATTRS=[mny]/CONFIG_SCSI_SRP_ATTRS=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_SCSI_CXGB3_ISCSI=[mny]/CONFIG_SCSI_CXGB3_ISCSI=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_SCSI_CXGB4_ISCSI=[mny]/CONFIG_SCSI_CXGB4_ISCSI=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_SCSI_BNX2_ISCSI=[mny]/CONFIG_SCSI_BNX2_ISCSI=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_BE2ISCSI=[mny]/CONFIG_BE2ISCSI=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_BLK_DEV_3W_XXXX_RAID=[mny]/CONFIG_BLK_DEV_3W_XXXX_RAID=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_SCSI_HPSA=[mny]/CONFIG_SCSI_HPSA=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_SCSI_3W_9XXX=[mny]/CONFIG_SCSI_3W_9XXX=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_SCSI_3W_SAS=[mny]/CONFIG_SCSI_3W_SAS=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_SCSI_ACARD=[mny]/CONFIG_SCSI_ACARD=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_SCSI_AIC7XXX=[mny]/CONFIG_SCSI_AIC7XXX=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_SCSI_AIC79XX=[mny]/CONFIG_SCSI_AIC79XX=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_SCSI_AIC94XX=[mny]/CONFIG_SCSI_AIC94XX=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_SCSI_MVSAS=[mny]/CONFIG_SCSI_MVSAS=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_SCSI_MVUMI=[mny]/CONFIG_SCSI_MVUMI=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_SCSI_ADVANSYS=[mny]/CONFIG_SCSI_ADVANSYS=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_SCSI_ARCMSR=[mny]/CONFIG_SCSI_ARCMSR=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_SCSI_ESAS2R=[mny]/CONFIG_SCSI_ESAS2R=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_LIBFC=[mny]/CONFIG_LIBFC=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_ATA=[mny]/CONFIG_ATA=m/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_ATA_ACPI=[mny]/CONFIG_ATA_ACPI=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_ATA_PIIX=[mny]/CONFIG_ATA_PIIX=m/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_SATA_MV=[mny]/CONFIG_SATA_MV=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_SATA_NV=[mny]/CONFIG_SATA_NV=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_SATA_PROMISE=[mny]/CONFIG_SATA_PROMISE=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_SATA_SIL=[mny]/CONFIG_SATA_SIL=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_SATA_SIS=[mny]/CONFIG_SATA_SIS=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_PATA_ALI=[mny]/CONFIG_PATA_ALI=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_PATA_AMD=[mny]/CONFIG_PATA_AMD=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_PATA_CMD640_PCI=[mny]/CONFIG_PATA_CMD640_PCI=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_REMOTE_TARGET=[mny]/CONFIG_REMOTE_TARGET=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_FUSION=[mny]/CONFIG_FUSION=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_FIREWIRE=[mny]/CONFIG_FIREWIRE=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_MACINTOSH_DRIVERS=[mny]/CONFIG_MACINTOSH_DRIVERS=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_MII=[mny]/CONFIG_MII=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_BAREUDP=[mny]/CONFIG_BAREUDP=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_GTP=[mny]/CONFIG_GTP=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_PFCP=[mny]/CONFIG_PFCP=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_AMT=[mny]/CONFIG_AMT=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_RIONET=[mny]/CONFIG_RIONET=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_SUNGEM_PHY=[mny]/CONFIG_SUNGEM_PHY=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_ATM_DRIVERS=[mny]/CONFIG_ATM_DRIVERS=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_ATM_DUMMY=[mny]/CONFIG_ATM_DUMMY=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_ATM_TCP=[mny]/CONFIG_ATM_TCP=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_NET_VENDOR_3COM=[mny]/CONFIG_NET_VENDOR_3COM=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_NET_VENDOR_ADAPTEC=[mny]/CONFIG_NET_VENDOR_ADAPTEC=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_NET_VENDOR_AGERE=[mny]/CONFIG_NET_VENDOR_AGERE=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_NET_VENDOR_ALACRITECH=[mny]/CONFIG_NET_VENDOR_ALACRITECH=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_NET_VENDOR_ALTEON=[mny]/CONFIG_NET_VENDOR_ALTEON=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_ALTERA_TSE=[mny]/CONFIG_ALTERA_TSE=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_NET_VENDOR_AMD=[mny]/CONFIG_NET_VENDOR_AMD=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_NET_VENDOR_AQUANTIA=[mny]/CONFIG_NET_VENDOR_AQUANTIA=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_NET_VENDOR_ARC=[mny]/CONFIG_NET_VENDOR_ARC=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_NET_VENDOR_CHELSIO=[mny]/CONFIG_NET_VENDOR_CHELSIO=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_NET_VENDOR_CAVIUM=[mny]/CONFIG_NET_VENDOR_CAVIUM=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_NET_VENDOR_CISCO=[mny]/CONFIG_NET_VENDOR_CISCO=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_NET_VENDOR_DEC=[mny]/CONFIG_NET_VENDOR_DEC=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_DNET=[mny]/CONFIG_DNET=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_NET_VENDOR_DLINK=[mny]/CONFIG_NET_VENDOR_DLINK=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_NET_VENDOR_EMULEX=[mny]/CONFIG_NET_VENDOR_EMULEX=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_E100=[mny]/CONFIG_E100=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_E1000=[mny]/CONFIG_E1000=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_E1000E=[mny]/CONFIG_E1000E=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_IGB=[mny]/CONFIG_IGB=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_IGBVF=[mny]/CONFIG_IGBVF=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_IXGBE=[mny]/CONFIG_IXGBE=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_I40E=[mny]/CONFIG_I40E=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_I40EVF=[mny]/CONFIG_I40EVF=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_ICE=[mny]/CONFIG_ICE=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_FM10K=[mny]/CONFIG_FM10K=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_IGC=[mny]/CONFIG_IGC=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_NET_VENDOR_MARVELL=[mny]/CONFIG_NET_VENDOR_MARVELL=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_MLX5_ESWITCH=[mny]/CONFIG_MLX5_ESWITCH=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_MLX5_MACSEC=[mny]/CONFIG_MLX5_MACSEC=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_MLX5_EN_IPSEC=[mny]/CONFIG_MLX5_EN_IPSEC=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_MLX5_SF=[mny]/CONFIG_MLX5_SF=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_FBNIC=[mny]/CONFIG_FBNIC=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_NET_VENDOR_MICREL=[mny]/CONFIG_NET_VENDOR_MICREL=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_NET_VENDOR_MICROCHIP=[mny]/CONFIG_NET_VENDOR_MICROCHIP=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_NET_VENDOR_NVIDIA=[mny]/CONFIG_NET_VENDOR_NVIDIA=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_NET_VENDOR_MYRI=[mny]/CONFIG_NET_VENDOR_MYRI=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_NET_VENDOR_OKI=[mny]/CONFIG_NET_VENDOR_OKI=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_NET_VENDOR_QLOGIC=[mny]/CONFIG_NET_VENDOR_QLOGIC=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_NET_VENDOR_BROCADE=[mny]/CONFIG_NET_VENDOR_BROCADE=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_NET_VENDOR_QUALCOMM=[mny]/CONFIG_NET_VENDOR_QUALCOMM=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_NET_VENDOR_RDC=[mny]/CONFIG_NET_VENDOR_RDC=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_NET_VENDOR_REALTEK=[mny]/CONFIG_NET_VENDOR_REALTEK=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_NET_VENDOR_SAMSUNG=[mny]/CONFIG_NET_VENDOR_SAMSUNG=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_NET_VENDOR_SUN=[mny]/CONFIG_NET_VENDOR_SUN=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_FDDI=[mny]/CONFIG_FDDI=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_PHYLIB=[mny]/CONFIG_PHYLIB=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_ETHOC=[mny]/CONFIG_ETHOC=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_MDIO_DEVICE=[mny]/CONFIG_MDIO_DEVICE=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_PCS_XPCS=[mny]/CONFIG_PCS_XPCS=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_PPP=[mny]/CONFIG_PPP=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_SLIP=[mny]/CONFIG_SLIP=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_WLAN=[mny]/CONFIG_WLAN=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_WAN=[mny]/CONFIG_WAN=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_WWAN_HWSIM=[mny]/CONFIG_WWAN_HWSIM=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_FUJITSU_ES=[mny]/CONFIG_FUJITSU_ES=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_ISDN=[mny]/CONFIG_ISDN=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_KEYBOARD_LKKBD=[mny]/CONFIG_KEYBOARD_LKKBD=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_INPUT_MISC=[mny]/CONFIG_INPUT_MISC=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_SERIO_SERPORT=[mny]/CONFIG_SERIO_SERPORT=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_SERIO_CT82C710=[mny]/CONFIG_SERIO_CT82C710=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_SERIO_PCIPS2=[mny]/CONFIG_SERIO_PCIPS2=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_SERIO_ALTERA_PS2=[mny]/CONFIG_SERIO_ALTERA_PS2=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_SERIO_PS2MULT=[mny]/CONFIG_SERIO_PS2MULT=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_SERIO_ARC_PS2=[mny]/CONFIG_SERIO_ARC_PS2=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_USERIO=[mny]/CONFIG_USERIO=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_GAMEPORT=[mny]/CONFIG_GAMEPORT=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_LEGACY_PTYS=[mny]/CONFIG_LEGACY_PTYS=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_SERIAL_JSM=[mny]/CONFIG_SERIAL_JSM=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_SERIAL_ARC=[mny]/CONFIG_SERIAL_ARC=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_N_GSM=[mny]/CONFIG_N_GSM=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_NOZOMI=[mny]/CONFIG_NOZOMI=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_NULL_TTY=[mny]/CONFIG_NULL_TTY=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_DEVPORT=[mny]/CONFIG_DEVPORT=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_I2C=[mny]/CONFIG_I2C=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_I3C=[mny]/CONFIG_I3C=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_SPI=[mny]/CONFIG_SPI=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_SPMI=[mny]/CONFIG_SPMI=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_HSI=[mny]/CONFIG_HSI=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_PTP_1588_CLOCK_MOCK=[mny]/CONFIG_PTP_1588_CLOCK_MOCK=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_PINCTRL=[mny]/CONFIG_PINCTRL=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_GPIOLIB=[mny]/CONFIG_GPIOLIB=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_W1=[mny]/CONFIG_W1=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_POWER_RESET=[mny]/CONFIG_POWER_RESET=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_POWER_SEQUENCING=[mny]/CONFIG_POWER_SEQUENCING=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_TEST_POWER=[mny]/CONFIG_TEST_POWER=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_BATTERY_DS2780=[mny]/CONFIG_BATTERY_DS2780=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_BATTERY_SAMSUNG_SDI=[mny]/CONFIG_BATTERY_SAMSUNG_SDI=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_BATTERY_DS2781=[mny]/CONFIG_BATTERY_DS2781=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_BATTERY_BQ27XXX=[mny]/CONFIG_BATTERY_BQ27XXX=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_CHARGER_MAX8903=[mny]/CONFIG_CHARGER_MAX8903=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_HWMON=[mny]/CONFIG_HWMON=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_THERMAL_EMULATION=[mny]/CONFIG_THERMAL_EMULATION=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_REGULATOR=[mny]/CONFIG_REGULATOR=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_RC_CORE=[mny]/CONFIG_RC_CORE=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_CEC_GPIO=[mny]/CONFIG_CEC_GPIO=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_MEDIA_SUPPORT=[mny]/CONFIG_MEDIA_SUPPORT=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_MEDIA_USB_SUPPORT=[mny]/CONFIG_MEDIA_USB_SUPPORT=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_USB_GSPCA=[mny]/CONFIG_USB_GSPCA=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_AUXDISPLAY=[mny]/CONFIG_AUXDISPLAY=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_AGP=[mny]/CONFIG_AGP=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_VGA_SWITCHEROO=[mny]/CONFIG_VGA_SWITCHEROO=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_DRM=[mny]/CONFIG_DRM=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_LCD_CLASS_DEVICE=[mny]/CONFIG_LCD_CLASS_DEVICE=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_BACKLIGHT_CLASS_DEVICE=[mny]/CONFIG_BACKLIGHT_CLASS_DEVICE=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_VGASTATE=[mny]/CONFIG_VGASTATE=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_HDMI=[mny]/CONFIG_HDMI=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_SOUND=[mny]/CONFIG_SOUND=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_HID_BPF=[mny]/CONFIG_HID_BPF=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_USB_HID=[mny]/CONFIG_USB_HID=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_HID_PID=[mny]/CONFIG_HID_PID=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_INTEL_ISH_HID=[mny]/CONFIG_INTEL_ISH_HID=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_USB_SUPPORT=[mny]/CONFIG_USB_SUPPORT=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_LEDS_CLASS_FLASH=[mny]/CONFIG_LEDS_CLASS_FLASH=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_ACCESSIBILITY=[mny]/CONFIG_ACCESSIBILITY=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_EDAC=[mny]/CONFIG_EDAC=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_RTC_NVMEM=[mny]/CONFIG_RTC_NVMEM=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_SYNC_FILE=[mny]/CONFIG_SYNC_FILE=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_VDPA_SIM=[mny]/CONFIG_VDPA_SIM=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_IFCVF=[mny]/CONFIG_IFCVF=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_GREYBUS=[mny]/CONFIG_GREYBUS=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_COMEDI_TESTS=[mny]/CONFIG_COMEDI_TESTS=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_CHROME_PLATFORMS=[mny]/CONFIG_CHROME_PLATFORMS=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_MELLANOX_PLATFORM=[mny]/CONFIG_MELLANOX_PLATFORM=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_X86_PLATFORM_DEVICES=[mny]/CONFIG_X86_PLATFORM_DEVICES=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_ALTERA_MBOX=[mny]/CONFIG_ALTERA_MBOX=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_REMOTEPROC=[mny]/CONFIG_REMOTEPROC=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_RPMSG=[mny]/CONFIG_RPMSG=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_PM_DEVFREQ=[mny]/CONFIG_PM_DEVFREQ=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_EXTCON=[mny]/CONFIG_EXTCON=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_LAN966X_OIC=[mny]/CONFIG_LAN966X_OIC=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_IPACK_BUS=[mny]/CONFIG_IPACK_BUS=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_RESET_CONTROLLER=[mny]/CONFIG_RESET_CONTROLLER=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_GENERIC_PHY=[mny]/CONFIG_GENERIC_PHY=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_PHY_CAN_TRANSCEIVER=[mny]/CONFIG_PHY_CAN_TRANSCEIVER=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_MCB=[mny]/CONFIG_MCB=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_AMD_ATL=[mny]/CONFIG_AMD_ATL=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_USB4=[mny]/CONFIG_USB4=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_ANDROID_BINDER_IPC=[mny]/CONFIG_ANDROID_BINDER_IPC=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_NVMEM=[mny]/CONFIG_NVMEM=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_INTEL_TH=[mny]/CONFIG_INTEL_TH=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_FPGA=[mny]/CONFIG_FPGA=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_SIOX=[mny]/CONFIG_SIOX=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_SLIMBUS=[mny]/CONFIG_SLIMBUS=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_INTERCONNECT=[mny]/CONFIG_INTERCONNECT=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_COUNTER=[mny]/CONFIG_COUNTER=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_MOST=[mny]/CONFIG_MOST=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_PECI=[mny]/CONFIG_PECI=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_HTE=[mny]/CONFIG_HTE=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_REISERFS_FS=[mny]/CONFIG_REISERFS_FS=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_JFS_FS=[mny]/CONFIG_JFS_FS=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_VIRTIO_FS=[mny]/CONFIG_VIRTIO_FS=y/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_NETFS_DEBUG=[mny]/CONFIG_NETFS_DEBUG=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_NTFS_FS=[mny]/CONFIG_NTFS_FS=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_DLM=[mny]/CONFIG_DLM=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_SECURITY_IPE=[mny]/CONFIG_SECURITY_IPE=y/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_CRYPTO_HW=[mny]/CONFIG_CRYPTO_HW=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_PKCS7_TEST_KEY=[mny]/CONFICONFIG_PKCS7_TEST_KEYG_CRYPTO_HW=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_PACKING=[mny]/CONFIG_PACKING=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_XZ_DEC_POWERPC=[mny]/CONFIG_XZ_DEC_POWERPC=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_XZ_DEC_ARM=[mny]/CONFIG_XZ_DEC_ARM=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_XZ_DEC_ARMTHUMB=[mny]/CONFIG_XZ_DEC_ARMTHUMB=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_XZ_DEC_TEST=[mny]/CONFIG_XZ_DEC_TEST=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_VMLINUX_MAP=[mny]/CONFIG_VMLINUX_MAP=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_TEST_MULDIV64=[mny]/CONFIG_TEST_MULDIV64=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_MEMTEST=[mny]/CONFIG_MEMTEST=n/g'  			${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_TEST_BPF=[mny]/CONFIG_TEST_BPF=n/g'  			${MAIN_KCONFIG_FILE}
  
  echo 'CONFIG_NF_CONNTRACK_PROCFS=y' 			>> ${MAIN_KCONFIG_FILE}
  
fi
		
#### cloud end

# build opt
echo 'CONFIG_LTO_CLANG_THIN=y' 			>> ${MAIN_KCONFIG_FILE}
echo 'CONFIG_DEBUG_INFO_COMPRESSED_ZLIB=y' 	    >> ${MAIN_KCONFIG_FILE}
echo 'CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE=y' 	>> ${MAIN_KCONFIG_FILE}
sed -i 's/CONFIG_KERNEL_/#CONFIG_KERNEL_/g'  	${MAIN_KCONFIG_FILE}
echo 'CONFIG_KERNEL_XZ=y' 	                >> ${MAIN_KCONFIG_FILE}
echo 'CONFIG_MODULE_COMPRESS=y' 	            >> ${MAIN_KCONFIG_FILE}
echo 'CONFIG_MODULE_COMPRESS_XZ=y' 	        >> ${MAIN_KCONFIG_FILE}

# Append a timestamp or something to the localversion to make it unique:
# echo "$( cat localversion )-$( date +%s )" > localversion
export DEBFULLNAME="Alexandre Frade"
export DEBEMAIL="kernel@xanmod.org"
export KDEB_CHANGELOG_DIST="bookworm"
#export KCONFIG_CONFIG="CONFIGS/xanmod/gcc/config_$psabi"

export lv=$(make -s kernelversion)
export xv=$(cat localversion)
export rv=0

PAREL_BUILD=$(nproc)
if [ "$PAREL_BUILD" -ge '8' ]; then
  PAREL_BUILD=8
fi
		
date; make olddefconfig LLVM=1 LLVM_IAS=1
date; make KDEB_COMPRESS=xz bindeb-pkg -j${PAREL_BUILD} LLVM=1 LLVM_IAS=1
date

# build perf
create_package() {
	local pname="$1" pdir="$2"
	local dpkg_deb_opts

	mkdir -m 755 -p "$pdir/DEBIAN"
	mkdir -p "$pdir/usr/share/doc/$pname"
	cp debian/copyright "$pdir/usr/share/doc/$pname/"
	cp debian/changelog "$pdir/usr/share/doc/$pname/changelog.Debian"
	gzip -n -9 "$pdir/usr/share/doc/$pname/changelog.Debian"
	sh -c "cd '$pdir'; find . -type f ! -path './DEBIAN/*' -printf '%P\\0' | xargs -r0 md5sum > DEBIAN/md5sums"

	# Fix ownership and permissions
	if [ "$DEB_RULES_REQUIRES_ROOT" = "no" ]; then
		dpkg_deb_opts="--root-owner-group"
	else
		sudo -E chown -R root:root "$pdir"
	fi
	# a+rX in case we are in a restrictive umask environment like 0077
	# ug-s in case we build in a setuid/setgid directory
	sudo -E chmod -R go-w,a+rX,ug-s "$pdir"

	# Create the package
	#dpkg-gencontrol -p$pname -P"$pdir"
	sudo -E cp ./debian/control "$pdir/DEBIAN/"
	sudo -E dpkg-deb $dpkg_deb_opts ${KDEB_COMPRESS:+-Z$KDEB_COMPRESS} --build "$pdir" ..
}

tools_version=$lv$pv$xv
tools_packagename=linux-tools
tools_destdir=./linux-tools-tmp
tools_destdir=`readlink -f $tools_destdir`
sudo -E rm -rf $tools_destdir || true

make -C ./tools/perf prefix=/usr DESTDIR=$tools_destdir install  NO_LIBZSTD=1 NO_LIBPERL=1  NO_LIBBABELTRACE=1
make -C ./tools/power/cpupower DESTDIR=$tools_destdir prefix=/usr install  NO_LIBZSTD=1 NO_LIBPERL=1 NO_LIBBABELTRACE=1

cat <<DEOF > debian/control   
Package: $tools_packagename
Architecture: amd64
Replaces: linux-base, linux-tools-common
Depends: libc6, libcap2, libdw1, libelf1, liblzma5, libnuma1, libpci3, libudev1, libunwind8, zlib1g
Description: Performance analysis tools for Linux $tools_version
 This package contains the 'perf' performance analysis tools for Linux
 kernel version $tools_version .
Maintainer: linux
Version: $tools_version

DEOF

# create perf deb
KDEB_COMPRESS=xz create_package \"$tools_packagename\" $tools_destdir

# build x64v3
cp ${MAIN_KCONFIG_FILE} ${MAIN_KCONFIG_FILE}.v2
if [[ $XANMOD_CONFIG =~ "-v2" ]]; then
  sed -i 's/x64v2/x64v3/g'  						${MAIN_KCONFIG_FILE}
  sed -i 's/CONFIG_X86_64_VERSION=2/CONFIG_X86_64_VERSION=3/g'  	${MAIN_KCONFIG_FILE}
  make olddefconfig LLVM=1 LLVM_IAS=1
  make KDEB_COMPRESS=xz bindeb-pkg -j${PAREL_BUILD} LLVM=1 LLVM_IAS=1
fi


# build cloud image
#rm ${MAIN_KCONFIG_FILE} || true
#cp -f ${MAIN_KCONFIG_FILE}.v2 ${MAIN_KCONFIG_FILE}

