name: xanmod edge kernel deb build by github

on:
  workflow_dispatch:
  schedule:
    - cron: 30 4 * * *

env:
  TZ: Asia/Shanghai
  BUILD_RUNNER: github
  BUILD_CLASS: edge
  BUILD_TYPE: std
  
jobs:
  Build:
    runs-on: ubuntu-22.04
    uses: ./.github/workflows/reuse_build_xanmod_kernel.yml
    secrets: inherit
