name: xanmod lts kernel deb by github

on:
  workflow_dispatch:
  schedule:
    - cron: 0 7 * * *

env:
  TZ: Asia/Shanghai
  BUILD_RUNNER: selfhost
  BUILD_CLASS: lts
  BUILD_TYPE: std
  
jobs:
  Build:
    runs-on: [self-hosted, Linux]
    uses: ./.github/workflows/reuse_build_xanmod_kernel.yml
    secrets: inherit
