name: xanmod main cloud kernel deb

on:
  workflow_dispatch:
  schedule:
    - cron: 10 0 * * *

env:
  TZ: Asia/Shanghai
  BUILD_RUNNER: github
  BUILD_CLASS: main
  BUILD_TYPE: cloud

jobs:
  Build:
    runs-on: ubuntu-22.04
    uses: ./.github/workflows/reuse_build_xanmod_kernel.yml
    secrets: inherit
